steps:
- id: "Rodando testes"
  name: "gcr.io/cloud-builders/go"
  args: ["test"]
  dir: "./src/"
  env: ["PROJECT_ROOT=main", "GOPATH=./src/"]

- id: "Gerando imagem e salvando no container registry"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/deploy-go-hpa:$SHORT_SHA", "."]

- id: "Push da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/deploy-go-hpa:$SHORT_SHA']

- id: 'Ajuste no arquivo de deployment'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#img-go-hpa-deployment#gcr.io/$PROJECT_ID/deploy-go-hpa:$SHORT_SHA#g' deployment.yaml > deployment-new.yaml;
      cat deployment-new.yaml;

- id: 'Efetuando deploy da aplicação'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'deployment-new.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

- id: 'Efetuando deploy do serviço'
  waitFor: ["Push da imagem"]
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'service.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
